function [x,fval]=LowSig(w,l,alf,Pgl,Pbl,par,x0)
lb=[par(5),par(5),par(5),-inf,0,0];
ub=[inf,inf,inf,0,inf,1];
[x,fval]=lsqnonlin(@solveL,x0,lb,ub);
    %nested function that computes all relevant Eq. objects
    function F = solveL(RL,RpL,piL)
    F=[...
        RL(1)-par(5)*((1-w)*l*(par(6)+(par(7)+par(8))*piL)+w*(1-l)*par(8)*(1-piL))/((1-w)*l*(par(6)+(par(7)+par(8))*piL)*par(1)+w*(1-l)*par(8)*(1-piL)*par(2));
        RL(2)-par(5)*((1-w)*l+w*(1-l))/((1-w)*l*par(1)+w*(1-l)*par(2));
        RL(3)-par(5)*((1-w)*l*par(8)*(1-piL)+w*(1-l)*(par(6)+(par(7)+par(8))*piL))/((1-w)*l*par(8)*(1-piL)*par(6)+w*(1-l)*(par(6)+(par(7)+par(8))*piL)*par(2));
        RpL(1)-par(5)*((1-w)*l*(par(6)+(par(7)+par(8))*piL)+w*(1-l)*par(8)*(1-piL))/((1-w)*l*(par(6)+(par(7)+par(8))*piL)*par(1)+w*(1-l)*par(8)*(1-piL)*par(2));
        RpL(3)-par(5)*w*l*(1-w)*(1-l)*par(8)*((par(6)+(par(7)+par(8))*piL)+par(7)*(1-piL)+par(8)*(1-piL))*(par(1)-par(2))/(((1-w)*l*par(8)*(1-piL)*par(6)+w*(1-l)*(par(6)+(par(7)+par(8))*piL)*par(2))^2);
        alf*piL^(alf-1)-(1/par(5))*(...
         Pgl*par(1)*...
          ((par(7)+par(8))*(par(3)-par(4)*RL(1))+(par(6)+(par(7)+par(8))*piL)*(-par(4))*RpL(1)...
          +(-par(7))*(par(3)-par(4)*RL(2))...
          +(-par(8))*(par(3)-par(4)*RL(3))+par(8)*(1-piL)*(-par(4))*RpL(3))...
        +Pbl*par(2)*...
          ((-par(8))*(par(3)-par(4)*RL(1))+par(8)*(1-piL)*(-par(4))*RpL(1)...
          +(-par(7))*(par(3)-par(4)*RL(2))...
          +(par(7)+par(8))*(par(3)-par(4)*RL(3))+(par(6)+(par(7)+par(8))*piL)*(-par(4))*RpL(3))...
        )...
    ];
    end
end