clear all;
tic

HiIG  = zeros(1,26);
LoIG  = zeros(1,26);
SG    = zeros(1,26);
Share = zeros(3,26);
Total = zeros(1,26);

% Below are the frequencies for each rating class
HiIG = ...
    [241; 272; 267; 237; 229; 229; ...
     222; 218; 202; 196; 192;      ...
     193; 186; 195; 182; 149;      ...
     141; 108; 105; 99;  94;       ...
     102; 104; 94;  76;  66];
LoIG = ...
    [503;  604;  606;  636;  654; 647; ...
     658;  699;  752;  773;  832;      ...
     906;  970;  1053; 1057; 1072;     ...
     1105; 1069; 1060; 1069; 1031;     ...
     979;  944;  929;  920;  891];
SG   = ...
    [317; 556; 611;  578; 543; 473; ...
     428; 441; 505;  550; 586;      ...
     650; 724; 823;  922; 944;      ...
     933; 984; 1001; 973; 933;      ...
     926; 864; 832;  809; 727];

        
for i=1:26
    Total(i)=HiIG(i)+LoIG(i)+SG(i);
    Share(1,i)=HiIG(i)/Total(i);
    Share(2,i)=LoIG(i)/Total(i);
    Share(3,i)=SG(i)/Total(i);
end

T=1:26;
periods = ...
    [1985:1:2010]';

figure('Name', 'Rating Frequencies','OuterPosition',[300 300 1000 750]);
hold on;
hHI=plot(T',HiIG');
hLO=plot(T',LoIG');
hSG=plot(T',SG');

set(hHI                             , ...
  'LineStyle'       , '-'            , ...
  'Color'           , rgb('lightcoral') , ...
  'LineWidth'       , 1              , ...
  'Marker'          , 'o'            , ...
  'MarkerSize'      , 6              , ...
  'MarkerEdgeColor' , rgb('lightcoral') , ...
  'MarkerFaceColor' , rgb('lightcoral') );

set(hLO                                , ...
  'LineStyle'       , '-'               , ...
  'Color'           , rgb('DarkViolet') , ...
  'LineWidth'       , 1                 , ...
  'Marker'          , 'o'               , ...
  'MarkerSize'      , 6                 , ...
  'MarkerEdgeColor' , rgb('DarkViolet') , ...
  'MarkerFaceColor' , rgb('DarkViolet') );

set(hSG                          , ...
  'LineStyle'       , '-'         , ...
  'Color'           , rgb('mediumseagreen') , ...
  'LineWidth'       , 1           , ...
  'Marker'          , 'o'         , ...
  'MarkerSize'      , 6           , ...
  'MarkerEdgeColor' , rgb('mediumseagreen') , ...
  'MarkerFaceColor' , rgb('mediumseagreen') );

hTitle  = title ('Rating Frequencies, by Rating Class');
hXLabel = xlabel('Year');
hYLabel = ylabel('Frequency');

hLegend = legend( ...
    [hHI, hLO, hSG],...
    'AAA or AA',...
    'A or BBB',...
    'BB or lower');

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hLegend, gca]             , ...
    'FontSize'   , 8           );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 10          );
set( hTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.01 .01] , ...
  'XMinorTick'  , 'off'     , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'XLim'        , [0 27]    , ...
  'XTick'       , 1:1:26    , ...
  'LineWidth'   , 1         );

set(gca,'XTickLabel',periods);

set(gcf, 'PaperPositionMode', 'auto');
print -dpng rate_freq.png
hold off;
close;

figure('Name', 'Rating Shares','OuterPosition',[300 300 1000 750]);
hold on;
hHI=plot(T',Share(1,:)');
hLO=plot(T',Share(2,:)');
hSG=plot(T',Share(3,:)');

set(hHI                             , ...
  'LineStyle'       , '-'            , ...
  'Color'           , rgb('lightcoral') , ...
  'LineWidth'       , 1              , ...
  'Marker'          , 'o'            , ...
  'MarkerSize'      , 6              , ...
  'MarkerEdgeColor' , rgb('lightcoral') , ...
  'MarkerFaceColor' , rgb('lightcoral') );

set(hLO                                , ...
  'LineStyle'       , '-'               , ...
  'Color'           , rgb('DarkViolet') , ...
  'LineWidth'       , 1                 , ...
  'Marker'          , 'o'               , ...
  'MarkerSize'      , 6                 , ...
  'MarkerEdgeColor' , rgb('DarkViolet') , ...
  'MarkerFaceColor' , rgb('DarkViolet') );

set(hSG                          , ...
  'LineStyle'       , '-'         , ...
  'Color'           , rgb('mediumseagreen') , ...
  'LineWidth'       , 1           , ...
  'Marker'          , 'o'         , ...
  'MarkerSize'      , 6           , ...
  'MarkerEdgeColor' , rgb('mediumseagreen') , ...
  'MarkerFaceColor' , rgb('mediumseagreen') );

hTitle  = title ('Rating Shares, by Rating Class');
hXLabel = xlabel('Year');
hYLabel = ylabel('Frequency');

hLegend = legend( ...
    [hHI, hLO, hSG],...
    'AAA or AA',...
    'A or BBB',...
    'BB or lower');...,...
    %'location', 'NorthEast');

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hLegend, gca]             , ...
    'FontSize'   , 8           );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 10          );
set( hTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.01 .01] , ...
  'XMinorTick'  , 'off'     , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'XLim'        , [0 27]    , ...
  'XTick'       , 1:1:26    , ...
  'LineWidth'   , 1         );

periods = ...
    [1985:1:2010]';

% periods = ...
%     ['1985';'1986';'1987';'1988';'1989';'1990';...
%      '1991';'1992';'1993';'1994';'1995'; ...
%      '1996';'1997';'1998';'1999';'2000'; ...
%      '2001';'2002';'2003';'2004';'2005'; ...
%      '2006';'2007';'2008';'2009';'2010'];
% 
set(gca,'XTickLabel',periods);

set(gcf, 'PaperPositionMode', 'auto');
print -dpng rate_share.png
hold off;
close;


toc




